### ISSUE TITLE
save into database - possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [consp1racy/android-support-preference#10]

**Comment by consp1racy** [comment]
When you create the preference fragment you can load default values from whatever source you choose. Use `findPreference(key);` to find the `Preference` you'd like to setup. Then you can add [`OnPreferenceChangeListener`](http://developer.android.com/reference/android/support/v7/preference/Preference.OnPreferenceChangeListener.html) to said `Preference` and store new values in the callback method.

It is beyond the scope of this library to provide tools for loading data from databases, content providers, network resources, etc.

**Comment by Rainer-Lang** [comment]
Thank you. This will help me a lot.
