### ISSUE TITLE
how to change step values in seekbarPreference?

### ISSUE THREAD

**Issue by EstherZeng** [consp1racy/android-support-preference#106]
and I want to save summary value of seekbar is number not percentage
what should I do?
Thanks!

**Comment by dirkam** [comment]
You can try to use `setSeekBarIncrement()` on your `SeekBarPreference`. With `setMin()` and `setMax()` you can specify the range. `getValue()` will give you the value and you can just set the summary based on your needs. Or better yet, you can listen to changes with `setOnSeekBarChangeListener()` and update the summary based on the current value.

**Comment by consp1racy** [comment]
Hi @EstherZeng, can you describe a particular use case?

**Comment by EstherZeng** [comment]
@dirkam  @consp1racy  Thanks you guys for help!  I solved this problem.
May I ask you a question? How counld I change text size in preference, default text size is kind of small.

**Comment by consp1racy** [comment]
@EstherZeng No problem!

Please see https://github.com/consp1racy/android-support-preference/issues/109. If you have more questions, please open separate issues. Thanks!
