### ISSUE TITLE
NumberPicker preference and color planned?

### ISSUE THREAD

**Issue by Rainer-Lang** [consp1racy/android-support-preference#11]

**Comment by consp1racy** [comment]
Hi, 
do you mean a classic Title+Summary preference which launches a dialog with NumberPicker?
I haven't seen `NumberPicker` used anywhere for a long time, it's not even mentioned in the Material design specs AFAIK. **`EditTextPreference` should fit your needs.**

**There are no plans to introduce `NumberPickerPreference` in this library.**

You are of course free to start whichever action you choose when your preference is clicked. Just override `onPreferenceTreeClick(boolean)` in your preference fragment:

```
@Override 
public boolean onPreferenceTreeClick(Preference preference) {
    if ("my_pref_key".equals(preference.getKey())) {
        // open custom dialog/activity/etc.
        return true;
    }
    return super.onPreferenceTreeClick(preference);
}
```

**Comment by JoseGD** [comment]
Hi @consp1racy and what about the 2nd part of the question, a color preference?

**Comment by consp1racy** [comment]
Hi, I probably won't go beyond AOSP and Material Design.

You can take any color picker library, make a dialog fragment out of it or start it as an activity for result and use plain `Preference` to start it.

In addition you can make a custom `ColorPreference` with custom widget layout which would show selected color on the right side. Take `CheckBoxPreference` as an example.

In time I may or may not implement this in the library but only the display part. Opening the color picker itself will be upon the developer allowing them to choose whichever library they prefer.

**Comment by JoseGD** [comment]
Thanks for your answer. Regarding the 1st line, a color picker is present in AOSP (see http://www.materialdoc.com/color-picker/), but you are right that is not listed among pickers in the MD documentation (https://www.google.com/design/spec/components/pickers.html)

**Comment by consp1racy** [comment]
@Rainer-Lang @JoseGD Alright, I just pushed a color preference implementation. Check out README on how to get it and use it. If you have more suggestions please open a new issue.

**Comment by JoseGD** [comment]
Thanks, I'll take a look
