### ISSUE TITLE
All labels should align with the left edge of the screen title

### ISSUE THREAD

**Issue by easdue** [consp1racy/android-support-preference#112]
All labels should align with the left edge of the screen title as listed here: https://material.io/design/platform-guidance/android-settings.html#label-secondary-text

**Comment by consp1racy** [comment]
This can easily be achieved by using an empty drawable for icon such as 

    android:icon="@android:color/transparent"

I'd like to leave the current implementation as is. 

Material design shows you some default suggestions, the final design language is ultimately your creation. I.e. you choose whether you want to align text with title or not.

Additionally I can provide a PreferenceThemeOverlay.Asp.Inset which sets the default icon of all preferences to an empty drawable.

**Comment by easdue** [comment]
The inset style sounds good. I've created my own style and all is well except for the PreferenceCategory. I can (until now) only get that aligned properly by creating my own layout for it with a 72dp left padding

**Comment by consp1racy** [comment]
Thanks for mentioning the PreferenceCategory. I'll check PreferenceScreen as well, since that one is also special.
