### ISSUE TITLE
PreferenceCategory title left margin/padding

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#114]
Is it expected with 2.3.1 that we no longer have left margin/padding for `PreferenceCategory` title on older APIs? (tested on API16)

Sorry if I missed this in the changelog and it is documented somewhere.

![image](https://user-images.githubusercontent.com/6302839/43595372-c598d9ac-967c-11e8-8bf0-fca3d53c9df6.png)

![image](https://user-images.githubusercontent.com/6302839/43595375-cbfa30de-967c-11e8-9e4e-5fe663980b21.png)

**Comment by consp1racy** [comment]
Thanks for the report. This is definitely a bug introduced when I added support for inset title on PreferenceCategory.

Try adding android:icon="@android:color/transparent" if that fits your needs.

**Comment by dirkam** [comment]
It adds too much padding so it is not a good workaround, unfortunately.

**Comment by consp1racy** [comment]
Correct, it assumes you have all text aligned with the title. See here: https://material.io/design/platform-guidance/android-settings.html#usage

In the meantime, if you want the old behavior, put this file in your project layouts:
https://github.com/consp1racy/android-support-preference/blob/f8b34662275fd4893028934a339b036567b64591/support-preference/src/main/res/layout/asp_preference_category.xml

**Comment by consp1racy** [comment]
This should be fixed in 7ec6b6e
