### ISSUE TITLE
xml attribute `android:inputType="number"` not working

### ISSUE THREAD

**Issue by rala72** [consp1racy/android-support-preference#115]
Like the title says I migrated from stock _(not support)_ to this lib which I used also in other apps too.
In my current migration I noticed, that the attribute `android:inputType="number"` is not working...

I'm trying to set it via Java now

> if someone has the same issue:
> don't create an EditText - just call `setOnEditTextCreatedListener()`

**Comment by consp1racy** [comment]
Glad you found it!

### The whole bit from readme

> <s>`EditTextPreference` understands `EditText` XML attributes.</s>
> Use `EditTextPreference.setOnCreateEditTextListener(OnCreateEditTextListener)` to setup your input field.

Plus there's a `app:asp_editTextLayout` attribute if you want to set up your EditText in XML. See here how it's used in the sample app:
https://github.com/consp1racy/android-support-preference/blob/e86bc258e01a31ac8fce16a063dd4c67e3778f21/sample/src/main/res/xml/pref_general.xml#L17
https://github.com/consp1racy/android-support-preference/blob/e86bc258e01a31ac8fce16a063dd4c67e3778f21/sample/src/main/res/layout/prefs_edit_example_text.xml

### f you're interested in technical reasons

The XML attributes from the preference are only available while the preference is inflating. So to understand the EditText attributes I'd have to inflate the EditText straight away. But at that point I don't have the appropriately themed context (with the dialog theme).

I could create the dialog themed context and prepare the EditText ahead of time but that's wasted CPU if the user never goes to the EditTextPreference.

I could go and manually add support for some or all attributes but I'd have to maintain it as new versions of Android roll out. And nobody should want to mess with with the beast EditText is. Matching the XML API to Java alone is a task for a whole afternoon.
