### ISSUE TITLE
please  help me how to set the item hight.

### ISSUE THREAD

**Issue by chongbo2013** [consp1racy/android-support-preference#13]
please  help me how to set the item hight.
beaucus,Preference hight  PreferenceScreen hight different Very ugly

and  how to set icon size,every icon different

**Comment by consp1racy** [comment]
Easiest way would be to change `android:layout` on your preference.

Presumably the `PreferenceScreen` item has only one line of text and therefore takes ~48dp height. Two line items have around 72dp height. This is correct behavior. See https://www.google.com/design/spec/patterns/settings.html#settings-usage.

**Comment by chongbo2013** [comment]
thank u
