### ISSUE TITLE
implementing SeekBar listeners

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#15]
Is it possible to implement SeekBarPreference onStartTrackingTouch and onStopTrackingTouch listeners?
If so, can someone provide a small sample code?

**Comment by consp1racy** [comment]
Subclass `SeekBarPreference` and override methods `onStartTrackingTouch` and `onStopTrackingTouch`.

If you just need to observe the final values attach an `OnPreferenceChangeListener` to the `SeekBarPreference`.

**Comment by dirkam** [comment]
Thanks. Awesome lib!

**Comment by dirkam** [comment]
is there a way to do the same with SeekBarPreferenceDialog? or somehow to get access to the seekbar?

**Comment by consp1racy** [comment]
Subclass `net.xpece.android.support.preference.XpSeekBarPreferenceDialogFragment`, you can access the `SeekBar` by calling `getSeekBar()`. Then set an `OnSeekBarChangeListener`.

You also need to display proper dialog fragment when the preference is clicked. Override the following method in your `XpPreferenceFragment`:

```
@Override
public void onDisplayPreferenceDialog(Preference preference) {
        if (this.getFragmentManager().findFragmentByTag("android.support.v7.preference.PreferenceFragment.DIALOG") == null) {
            DialogFragment f;
            if (preference instanceof SeekBarDialogPreference) {
                f = YourCustomSeekBarPreferenceDialogFragment.newInstance(preference.getKey());
            } else {
                super.onDisplayPreferenceDialog(preference);
                return;
            }

            f.setTargetFragment(this, 0);
            f.show(this.getFragmentManager(), "android.support.v7.preference.PreferenceFragment.DIALOG");
        }
    }
}
```

**Don't forget to create new `newInstance` method in the dialog fragment.**

**Comment by dirkam** [comment]
I can't find getSeekBar().
Isn't there a way to do this extending SeekBarDialogPreference?

**Comment by consp1racy** [comment]
As I said, the seek bar is in `XpSeekBarPreferenceDialogFragment` not `SeekBarDialogPreference`. You need to (1) subclass the dialog fragment correctly, (2) call your custom dialog fragment instead of the old one.

**Comment by dirkam** [comment]
May I have one more question? What View parameter should I pass to getSeekBar()?

**Comment by dirkam** [comment]
overriding onBindDialogView solved it, thanks

**Comment by consp1racy** [comment]
Yes, assign the listener in `onBindDialogView`. Totally forgot to mention it. Good job!
