### ISSUE TITLE
preference  save configuration bug.

### ISSUE THREAD

**Issue by chongbo2013** [consp1racy/android-support-preference#16]
on  OnPreferenceChangeListener  be called,

String value=PreferenceManager.getDefaultSharedPreferences(preference.getContext()).getString(preference.getKey(), R.string.xxx); 

the value is  not the new. 

private static Preference.OnPreferenceChangeListener sBindPreferenceSummaryToValueListener = new Preference.OnPreferenceChangeListener() {
        @Override
        public boolean onPreferenceChange(Preference preference, Object value) {

```
        if (preference.getKey().equals(preference.getContext().getString(R.string.preference_key_left_screen))) {
            Boolean stringValue = (Boolean)value;
            FlyLauncherProSetting.LEFT_SCRENN_ENABLE=stringValue;
        }
```

//  call refresh the UI

```
        return true;
    }
};
```

**Comment by consp1racy** [comment]
At the point you're asking the new value isn't stored yet.

**Comment by chongbo2013** [comment]
onPreferenceChange  Method    do   String value=PreferenceManager.getDefaultSharedPreferences(preference.getContext()).getString(preference.getKey(), R.string.xxx);      the  value   Is not the latest change value.

**Comment by consp1racy** [comment]
```
//                                                              v this is the new value
public boolean onPreferenceChange(Preference preference, Object value)
```

`R.string.xxx` is the default value if there is nothing saved yet.

I can't see where the problem could be, `EditTextPreference` works in the sample project.
