### ISSUE TITLE
please  help me .

### ISSUE THREAD

**Issue by chongbo2013** [consp1racy/android-support-preference#18]
![qq 20151225163653](https://cloud.githubusercontent.com/assets/3191545/12001592/4d359e44-ab26-11e5-97aa-7df30161b3c9.png)
please  help me .

**Comment by consp1racy** [comment]
### The 'NEW' icon

Make a XML layout file with TextView and text 'NEW'.
Point `android:widgetLayout` of your preference to that layout.
Remember, you can only have one widget per preference, e.g. this would overwrite Switch in SwitchPreference and crash.

### Theme

Just change your activity theme.
