### ISSUE TITLE
How can did preference RTL and LTR  

### ISSUE THREAD

**Issue by shahinesi** [consp1racy/android-support-preference#19]
i have ur preference  RTL and LTR from api 7+ or 8+
is it possible?
Tnx

**Comment by consp1racy** [comment]
I think it's possible to have RTL layouts. Copy the layout files from the library into your project and flip them manually.

**Comment by shahinesi** [comment]
OK, so flip them automatic ,it's not possible?
tnx

**Comment by consp1racy** [comment]
Native RTL is only supported on Android 4.2+ (API 17).
