### ISSUE TITLE
How to build the library and sample?

### ISSUE THREAD

**Issue by janpfeil** [consp1racy/android-support-preference#20]
I did 
`git clone`
the project and then inside it I run
`./gradlew clean build`
which gives me a lot of errors (cannot find symbol, .. does not exist).
Can you provide build instructions?

**Comment by consp1racy** [comment]
Pull the latest commit. I fixed some lint errors and disabled doclint on Java 8.

If you still can't build the project go to File > Project Settings and change JDK to 1.7.0_something.

If that still doesn't work, post me the errors. The gradle build output will be fine, "a lot of errors" means nothing here.

**Comment by janpfeil** [comment]
Thank you very much, that did the trick. I run the gradlew build successfully now. 
Deployment was fine.
In AndroidStudio I still get an error on the sample module (asp_simpleMenu is 
not found):

Executing task ':sample:processDebugResources' (up-to-date check took 
0.006 secs) due to:
  Value of input property 'preferredDensity' has changed for task 
':sample:processDebugResources'
All input files are considered out-of-date for incremental task 
':sample:processDebugResources'.
Starting process 'command '/opt/android/android-sdk-linux/build-
tools/23.0.2/aapt''. Working directory: 
/opt/projects/android3rd.workspace/android-support-preference/sample 
Command: /opt/android/android-sdk-linux/build-tools/23.0.2/aapt package -f --
no-crunch -I /opt/android/android-sdk-linux/platforms/android-23/android.jar -M 
/opt/projects/android3rd.workspace/android-support-
preference/sample/build/intermediates/manifests/full/debug/AndroidManifest.x
ml -S /opt/projects/android3rd.workspace/android-support-
preference/sample/build/intermediates/res/merged/debug -A 
/opt/projects/android3rd.workspace/android-support-
preference/sample/build/intermediates/assets/debug -m -J 
/opt/projects/android3rd.workspace/android-support-
preference/sample/build/generated/source/r/debug -F 
/opt/projects/android3rd.workspace/android-support-
preference/sample/build/intermediates/res/resources-debug.ap_ --debug-
mode --custom-package net.xpece.android.support.preference.sample -0 apk --
output-text-symbols /opt/projects/android3rd.workspace/android-support-
preference/sample/build/intermediates/symbols/debug --no-version-vectors
Successfully started process 'command '/opt/android/android-sdk-linux/build-
tools/23.0.2/aapt''
/opt/projects/android3rd.workspace/android-support-
preference/sample/src/main/res/xml/pref_data_sync.xml
Error:(5) No resource identifier found for attribute 'asp_simpleMenu' in package 
'net.xpece.android.support.preference.sample'
:sample:processDebugResources FAILED
:sample:processDebugResources (Thread[Daemon worker Thread 3,5,main]) 
completed. Took 0.161 secs.
FAILURE: Build failed with an exception.
Information:BUILD FAILED
Information:Total time: 4.708 secs
Stopped 0 compiler daemon(s).
Information:1 error
Information:0 warnings
Information:See complete output in console

Can you reproduce this or have any suggestion?

**Comment by consp1racy** [comment]
Build > Rebuild Project. If that doesn't work then File > Invalidate Caches / Restart. If that doesn't work, well, I have no idea :D

If it builds from command line Android Studio should pick it up eventually as well.
