### ISSUE TITLE
build error with support library version of 23.2.0

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#22]
If version 23.2.0 of support libraries are used then I get some errors like:
Error:(2) Attribute "preferenceStyle" has already been defined
Error:(2) Attribute "checkBoxPreferenceStyle" has already been defined
Error:(2) Attribute "dialogPreferenceStyle" has already been defined
Error:(2) Attribute "editTextPreferenceStyle" has already been defined
Error:(2) Attribute "ringtonePreferenceStyle" has already been defined
Error:(2) Attribute "switchPreferenceStyle" has already been defined
Error:(2) Attribute "seekBarPreferenceStyle" has already been defined
Error:(2) Attribute "preferenceScreenStyle" has already been defined
Error:(2) Attribute "preferenceFragmentListStyle" has already been defined

Would it be resolved if you updated your library with these support libraries? If so, can you please do that?

**Comment by consp1racy** [comment]
Yeah, there are more incompatibilities than this. Stick to 23.1.1 support libs for now and stay tuned for 0.5.5 release of this lib.

**Comment by dirkam** [comment]
Do you happen to have any estimates on when could you prepare the 0.5.5 release? I'd really need to use the new support lib for other reasons and it'd help to know this.

Thanks for the awesome lib.

**Comment by consp1racy** [comment]
It should be out by now. Sadly it won't be compatible with older versions of the support lib.

**Comment by dirkam** [comment]
Thanks

**Comment by dirkam** [comment]
Is it normal that with this version I can see a different bg color for the preference items and there is also a divider among the preferences?

**Comment by consp1racy** [comment]
Can you post a screenshot?

I think the dividers are now provided by preference-v7 by default. Didn't hear anything about a background.

**Comment by dirkam** [comment]
Indeed, it seems that the divider has been there with 0.5.3 as well.
Previously with 0.5.3:

Now with 0.5.5:

Light theme:

**Comment by consp1racy** [comment]
**Dividers**

I just added this to `README.md` section about dividers:

> Looks like this is not necessary in 0.5.5 as preference-v7 r23.2.0 provides a default divider. If you want to customize how this divider looks you can call `setDivider(...)` and `setDividerHeight(...)`. Preference-v7 divider will be drawn just between items and at the bottom of the list. It will not be drawn before the end of category. You can disable this default divider with `setDivider(null)` and continue using what I described above.

You have two options:

_1)_ Disable the divider provided by preference-v7 by calling

```
setDivider(null)
```

_2)_ Disable my divider by removing

```
list.addItemDecoration(new PreferenceDividerDecoration(getContext()).drawBottom(true));
```

**Background**

As for the background I got nothing, it does not happen on my phone.

The light theme gives me some clues. You're testing in an emulator. Press Tab, the focus changes and from there everything should be ok. Don't know why this happens, it's not my fault, report Android bug if you feel this shouldn't be happening.

**Comment by dirkam** [comment]
Thanks for the update.
Indeed, on a physical device I can't see the blueish bg color, however I can still see the bg color that is different from the rest of the screen.
It must be related to this library or the 23.2.0 version of the support one as nothing else has changed in my code.
So you have checked it and you can't see the change in the bg color?

One more question:
If you check the screenshots you can see that the bottom preference has a different margin around the icon. That one is a listpreference while the other ones are preferencescreen items. Is this intentional?

**Comment by consp1racy** [comment]
I dunno. Review your theme attributes. Nothing changed on my part besides depending on preference-v7 23.2.0. Did you change `selectableItemBackground`?

About the other question read this https://github.com/consp1racy/android-support-preference#handling-preferencescreen-icons

**Comment by dirkam** [comment]
Thanks for your help. Indeed it seems that the background comes from selection. On emulator by pressing TAB confirms this. What's strange is that I can also see this on physical devices. Except that I can't press TAB there so I can't confirm this but it seems so. Any ideas?

**Comment by consp1racy** [comment]
I've got nothing. Must be from overriding some theme attribute, no other ideas come to mind.

**Comment by PaulNeesham** [comment]
Hi, I'm using your library and its great but I'm getting the background color problem on all the devices I try it on, just wondering if you've had any ideas on what's causing it?

**Comment by consp1racy** [comment]
@PaulNeesham @dirkam Ok, I've looked into it; it's caused by `RecyclerView` bringing focus to itself. We can disable this while having its child views behave correctly.

Symptoms are holo blue background on Android 4 and grey background on Android 5 when the fragment starts.

Solution is to disable focusability on the `RecyclerView` itself.

```
@Override
public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    final RecyclerView listView = getListView();

    // We don't want this. The children are still focusable.
    listView.setFocusable(false);
}
```

**Comment by PaulNeesham** [comment]
Wow fast response! Tried it on few device and solves it. Cheers!

**Comment by JoseGD** [comment]
Hi Eugene, any chance to get this code in the library itself?

**Comment by consp1racy** [comment]
@JoseGD Technically it is possible in multiple ways but let's keep it opt-in. The original works as the support library developers intended (I hope) and you as the product developer now have the tools to alter that behavior. Agreed?

It's a couple of lines, it's documented in README and you can apply it in this wording to either `PreferenceFragment` or `XpPreferenceFragment` one of which you have to extend.

**Comment by JoseGD** [comment]
Ok, not problems at all to add just a couple of lines, I asked that because I've seen similar tricks have been applied in the past and future versions of this library made them unnecessary.
By the way, thanks for keeping the readme updated, didn't notice that addition
