### ISSUE TITLE
AccessibilityManager causes CheckBoxPreference not checked

### ISSUE THREAD

**Issue by anggrayudi** [consp1racy/android-support-preference#23]
I don't know why you only put below code in `SwitchPreference` and `CheckBoxPreference`, while another preferences don't have it. Sometimes, `accessibilityManager.isEnabled()` returns `false`, and sometimes returns `true`. This makes `SwitchPreference` and `CheckBoxPreference` sometimes checked, and sometimes not checked. Can you explain the purpose of below code and fix this bug?

```
AccessibilityManager accessibilityManager = (AccessibilityManager) getContext().getSystemService(Context.ACCESSIBILITY_SERVICE);
if (accessibilityManager.isEnabled()) {
    ...
}
```

**Comment by consp1racy** [comment]
Hello,

> I don't know why you only put below code in SwitchPreference and CheckBoxPreference, while another preferences don't have it.

It's there because original classes from `android.support.v7.preference` have it.

> Sometimes, accessibilityManager.isEnabled() returns false, and sometimes returns true.

Such is life.

> This makes SwitchPreference and CheckBoxPreference sometimes checked, and sometimes not checked. 

How? The code just synchronizes state and does not call `setChecked(boolean)`. I just commented the code and it behaves all the same for the sample app.

> Can you explain the purpose of below code 

Not really, as far as I can see it does nothing. It's there to mimic classes from preference-v7 library.

> and fix this bug?

As mentioned before, I see no bug. Perhaps upload a video of expected/current behavior and/or your code and better describe the issue. A bunch of "sometimes" really isn't enough to pinpoint what's going on.

**Comment by anggrayudi** [comment]
I have captured the video to show you the bug. Watch this gif. You will notice that `SwitchPreference` still has these bugs:
1) Can't switch its state.
2) After we click `SwitchPreference`. Scroll it down and scroll up again, suddenly its state was changed.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/12292380/13640075/ff301836-e645-11e5-8fa2-7d557fb1a751.gif)

**Comment by consp1racy** [comment]
Would it be ok to share your **preference fragment source file** and **preference XML resource**? I'll take a look at it and compare it to the sample app to see what we can do about it.

In the meantime try `compile 'com.android.support:preference-v7:23.2.0'` (or 23.1.1) instead to see if plain support lib also causes this issue.

**Comment by anggrayudi** [comment]
This is my code. I have removed `AccessibilityManager` from `CheckBoxPreference` and `SwitchPreference`. Since that, both of them work correctly.

But, I'm sorry, I have changed your package name because your package name is too long. This waste my time to write the preference in XML. Also, the package name consumes Android Studio project explorer's space. I advise you to change it from `net.xpece.android.support.preference` to `net.xpece.preference` which is shorter. I believe that other developers encounter the same problem with your package name.

[anggrayudi_code.gz](https://github.com/consp1racy/android-support-preference/files/166718/anggrayudi_code.gz)

**Comment by consp1racy** [comment]
Again, can I get your preference fragment source code? I need to know how are you using the library. Please post anything that concerns preferences. Also what devices does this happen on? Please be specific: vendor and model number, version of android.

---

Alright, for now, copy those two classes in your package and I'll investigate further. You can override `getCustomDefaultPackages` so you don't have to write your package name all the time like a slave:

```
@Override
public String[] getCustomDefaultPackages() {
    return new String[]{"com.anggrayudi.settings.preference."};
}
```

And if you read the sample app you'll know you don't have to use package names in XML with my preferences as long as you extend `XpPreferenceFragment`. So thanks for the advice but no, thanks.

---

You haven't included `com.anggrayudi.settings.preference.Preference`. Your version of `TwoStatePreference` extends from this class and this class is not one of mine, afaik you're de facto not using my library and I can't be held responsible.

BTW what the hell is this? It was working out of the box, I wonder where else you're circumventing how the support preference library works. No wonder it's breaking.

```
public TwoStatePreference(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
    super(context, attrs, defStyleAttr, defStyleRes);
    // Obtaining mChecked last value from this constructor is better than you call setChecked in
    // onSetInitialValue, because sometimes 'Object defaultValue' returns null.
    // Also, we should not use getPersisted*() method in constructor. We have to retrieve the last value by
    // using getPreferences() method which returns PreferenceManager.getDefaultSharedPreferences().
    // I have added this method into Preference class.
    boolean mDefaultValue = attrs.getAttributeBooleanValue(Preferences.ANDROID_NS, "defaultValue", false);
    mChecked = getPreferences().getBoolean(getKey(), mDefaultValue);
}
```

**Comment by anggrayudi** [comment]
I only change the package name from `net.xpece.android.support.preference.Preference` to `com.anggrayudi.settings.preference.Preference`, then I added this method to this class:

```
public SharedPreferences getPreferences(){
    return PreferenceManager.getDefaultSharedPreferences(getContext());
}
```

---

Look at above constructor you quoted. I don't know why `getPersistedBoolean(false)` always return `false` where `false` is the default value. So that, I add `getPreferences()` method. I use this method to avoid `onSetInitialValue(boolean restoreValue, Object defaultValue)` from returning `defaultValue` parameter to `null` object. I don't know why sometimes `defaultValue` returns `null`.

---

> I need to know how are you using the library. 

I use your library just like your sample on `SettingsFragment` class.

---

Now, everything works fine.

**Comment by anggrayudi** [comment]
BTW, does change your package name is a violation for you though I include the library's license?

Thanks.

**Comment by consp1racy** [comment]
> I don't know why getPersistedBoolean(false) always return false

This method will always return default value when you set `android:persistent="false"`. So in order to retain correct value after e.g. a screen orientation change for non-peristed preferences the framework uses the `restoreValue` argument in `onSetInitialValue(boolean restoreValue, Object defaultValue)`. You may have circumvented this feature in that constructor.

---

It's open source so you can twist it as you like but I may not be able to help you if something breaks.

Other than this, I hope the library is serving you well.

**Comment by anggrayudi** [comment]
Thanks for your explanation. This method `onSetInitialValue(boolean restoreValue, Object defaultValue)` gave me a headache over many days.

You're doing a great favor!
