### ISSUE TITLE
Request: FolderChooserPreference

### ISSUE THREAD

**Issue by anggrayudi** [consp1racy/android-support-preference#26]
Hi there, I have a feature request for your library, i.e. `FolderChooserPreference`. This preference makes developers able to ask the user to choose the save path. Also, disable the _choose_ button if the path is not writable and don't forget to add _back_ button for the dialog.

Thanks in advance.

**Comment by consp1racy** [comment]
Hello, could you provide a use case for this feature?

**Comment by anggrayudi** [comment]
@consp1racy For example, I'm making an app that can download files. I want to make a preference to get the save path. Once the file was downloaded, it will be moved to the that path. Users can choose where they want to save the downloaded file by default.

Another example is, I'm making an app that can edit photos, let's say a JPG file. I want to make a preference to get the save path. Once user click _OK_ which means editing was complete, the file (JPG) will be saved to the path that is stored in the preference.

There are many uses for this preference. I couldn't tell you all.

**Comment by consp1racy** [comment]
Mobile phone/tablet is a device for simple tasks, or at least presents tasks in simple manner. <s>The user</s> Most users will <s>probably</s> not care, where the file is stored as long as they have access to it again in a simple way. 

My suggestion: Manage the file location based on an internal algorithm and provide a way to sort them via group name or tags. These can be stored in a database, not file path or file name - abstract from file name.

If you really need this, find a library that suits you here https://android-arsenal.com/tag/35. Then you can have a plain `Preference` start an activity for result etc.
