### ISSUE TITLE
Scroll position when returning from subscreen

### ISSUE THREAD

**Issue by JoseGD** [consp1racy/android-support-preference#28]
I don't know if this is intended or it's a bug:

I have a somewhat long list of preferences, and a pair of subscreen items that can be reached after scrolling the list a bit. I enter one of the subscreens and when I return the main settings list is reset to the top, losing the scroll position.

**Comment by consp1racy** [comment]
I'm assuming you're using `PreferenceScreenNavigationStrategy.ReplaceRoot`. This was the first solution I've come up with and is quite inferior to `PreferenceScreenNavigationStrategy.ReplaceFragment` which supports transaction animations and most importantly back stack, which means it remembers stuff like scroll position even across orientation changes when navigating between subscreens.

My suggestion is to migrate to `ReplaceFragment` strategy. Documentation may be somewhat lacking but the sample app is using this approach so start there.

Notes:
Updating `ReplaceRoot` strategy will require remembering this for each subscreen:
- topmost visible child position
- visible pixel height of said child

**Comment by JoseGD** [comment]
You assumed right. My code was written prior to the introduction of `ReplaceFragment` and keeping `ReplaceRoot` was easier for me.
Will take a look at `ReplaceFragment` then. Thank you

**Comment by consp1racy** [comment]
I tried to replicate the scroll position as precise as possible but could only round the first visible child to be completely visible. Which is still better than nothing.

While at it I marked `ReplaceRoot` as deprecated.

**Comment by JoseGD** [comment]
For me the scroll position is being preserved (almost) well. Thanks!
I will migrate to `ReplaceFragment` as soon as possible, of course.

**Comment by consp1racy** [comment]
You inspired me to look into it some more and indeed there is a way to restore scroll position perfectly. Thank you. This will be fixed in 0.7.1. However I fully support your decision to move to `RepolaceFragment`.
