### ISSUE TITLE
Ringtone Preference not working...

### ISSUE THREAD

**Issue by KennyGoers** [consp1racy/android-support-preference#3]
I tried in both my app and the sample application when cloning the current code base, the Ringtone picker crashes with: String resource ID #0x0 not found. This is on an 4.4 emulator. I'll see if I can contribute...

**Comment by consp1racy** [comment]
Ringtone picker takes some of its strings from the music provider package (presumably on all devices) and falls back to english ones included with the library. I did not observe any errors while testing. Please feel free to investigate. Thank you.

**Comment by KennyGoers** [comment]
The pull request corrects this problem.

**Comment by consp1racy** [comment]
Published in 0.4.3.
