### ISSUE TITLE
PreferenceScreenNavigationStrategy question

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#32]
Hi,

I was using 0.6.2 and updated to 0.8.0 recently. Now I just noticed that I have an issue with preference navigation strategy.

I use the following:

``` java
private PreferenceScreenNavigationStrategy.ReplaceRoot mPreferenceScreenNavigation;

if (mPreferenceScreenNavigation == null) {
                    mPreferenceScreenNavigation = new PreferenceScreenNavigationStrategy.ReplaceRoot(this, this);
                    mPreferenceScreenNavigation.onCreatePreferences(paramBundle);
                }
```

``` java
@Override
    public boolean onPreferenceTreeClick(Preference preference) {
        if (preference instanceof PreferenceScreen) {
            PreferenceScreen preferenceScreen = (PreferenceScreen) preference;
            mPreferenceScreenNavigation.onPreferenceScreenClick(preferenceScreen);
            return true;
        }
        return super.onPreferenceTreeClick(preference);
    }
```

If I just simply click on a PreferenceScreen then it's all OK. But if I try to use

``` java
mPreferenceScreenNavigation.onPreferenceScreenClick(mPreference);
```

then I get NPE.

``` java
java.lang.NullPointerException
net.xpece.android.support.preference.PreferenceScreenNavigationStrategy$ReplaceRoot.navigateToPreferenceScreen(PreferenceScreenNavigationStrategy.java:193)
net.xpece.android.support.preference.PreferenceScreenNavigationStrategy$ReplaceRoot.onPreferenceScreenClick(PreferenceScreenNavigationStrategy.java:247)
```

It was working with 0.6.2. I don't really want to migrate to ReplaceFragment at this point in time.
Is there a way to make this work with 0.8.0?

**Comment by consp1racy** [comment]
Any calls to `onPreferenceScreenClick` must occur between `onViewCreated` and `onDestroyView`.

**Comment by dirkam** [comment]
I call it from onCreatePreferences2 as I used to. Tried to move it to onStart but it's the same.
What do I do wrong?

**Comment by consp1racy** [comment]
Found it. `ReplaceRoot.onCreatePreferences(savedInstanceState)` has to be called in any case. It handles restoring correct screen. Move it outside the `if` block.

```
if (mPreferenceScreenNavigation == null) {
    mPreferenceScreenNavigation = new PreferenceScreenNavigationStrategy.ReplaceRoot(this, this);
}
mPreferenceScreenNavigation.onCreatePreferences(paramBundle);
```

Then keep `onPreferenceScreenClick` only in `onPreferenceTreeClick`.

**Comment by dirkam** [comment]
Moved it outside the `if` block. I still get the NPE.

> Then keep `onPreferenceScreenClick` only in `onPreferenceTreeClick`.

I'm not sure I get this. Isn't `mPreferenceScreenNavigation.onPreferenceScreenClick(preference);` OK to use?

Thanks for your help.

**Comment by consp1racy** [comment]
> Any calls to `onPreferenceScreenClick` must occur between `onViewCreated` and `onDestroyView`.

The method needs the recycler view initialized which happens in `onCreateView`.

There's no point in calling `onPreferenceScreenClick` anywhere else than `onPreferenceTreeClick`. What's your intention?

**Comment by dirkam** [comment]
I'd like to note that this was working absolutely fine with 0.6.2.
I have a preferences structure where I have nested preferencescreens:

```
Main Screen 1
    Sub Screen 1
    Sub Screen 2
Main Screen 2
    Sub Screen 1
    Sub Screen 2
...
```

If a user clicks on Settings menu, then I want to show

```
Main Screen 1
Main Screen 2
...
```

However, if a user clicks on a particular button, then I want to open directly `Sub Screen 1` of `Main Screen 1`

For this, I used `mPreferenceScreenNavigation.onPreferenceScreenClick(preference);` (used to call it from onCreatePreferences2 if a certain flag was set in the param Bundle), which was imitating a user click and was working fine.

What would be the proper way to achieve this if this is not appropriate?

**Comment by consp1racy** [comment]
That's a use case I haven't anticipated. Will be fixed in next release - as soon as I investigate https://github.com/consp1racy/android-support-preference/issues/30.

In the meantime try moving it to `onResume`. If that doesn't work copy the latest version of `ReplaceRoot` from [here](https://github.com/consp1racy/android-support-preference/blob/master/library/src/main/java/net/xpece/android/support/preference/PreferenceScreenNavigationStrategy.java) into your project and use that until it's released.

**Comment by dirkam** [comment]
Works like a charm. Thanks for the prompt help.
