### ISSUE TITLE
Time Picker Preference plans?

### ISSUE THREAD

**Issue by marcinkunert** [consp1racy/android-support-preference#33]
Are there any plans to introduce a support time picker preference?

**Comment by consp1racy** [comment]
1) Time picker of your choice can be invoked via [`OnPreferenceTreeClickListener`](http://developer.android.com/reference/android/support/v7/preference/PreferenceManager.OnPreferenceTreeClickListener.html).
2) Report back the result via mechanism of your design. If picker is inside a fragment you can `setTargetFragment(settingsFragment)` before invoking it so you can `getTargetFragment()` from the picker fragment. Or the picker fragment can update `SharedPreferences` directly.
3) Change in preference value can be observed via [`OnPreferenceChangeListener`](http://developer.android.com/reference/android/support/v7/preference/Preference.OnPreferenceChangeListener.html).

If you're looking for a backport of Material Design time and date pickers, you won't find them here as they're beyond the scope of this library.

Suggested links:
https://github.com/wdullaer/MaterialDateTimePicker
https://android-arsenal.com/tag/27
