### ISSUE TITLE
support-preference without support-spinner

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#35]
Hi there,

Since there is a separate version for support-spinner only, would it be possible to have the support-preference without it?
I tried to exclude this module in my dependency list but then I get errors with missing parent themes.

Thanks

**Comment by consp1racy** [comment]
What's the real issue?

This is intended for a case where you want a drop down menu as in MD specs but don't necessarily need preferences, not the other way around.

There was a time when support-spinner was part of support-preference so the question wouldn't even come into play. (Which also means it wouldn't help your method reference count in any way if there was not a separate support-spinner lib.)

**Comment by dirkam** [comment]
`net.xpece.android:support-preference:0.8.1` pulls `support-spinner`

```
+--- net.xpece.android:support-preference:0.8.1
|    +--- com.android.support:appcompat-v7:23.3.0 -> 23.4.0 (*)
|    +--- net.xpece.android:support-spinner:[0.8.0,0.9.0) -> 0.8.1
|    |    \--- com.android.support:appcompat-v7:23.3.0 -> 23.4.0 (*)
|    \--- com.android.support:preference-v7:23.3.0 -> 23.4.0 (*)
```

I wonder if it would be possible to use `support-preference` without having `support-spinner`?

I don't really need the spinner, and I believe that in most cases it's not needed. Since it's available as a separate lib if someone would need it then both lib should be pulled.

**Comment by consp1racy** [comment]
I understand the question but **having a library is an artifical issue. What's the real issue?** Do you think it would significantly decrease build time, help you with dex method limit..? What are you really after?

Here's how heavy the library is: http://www.methodscount.com/?lib=net.xpece.android%3Asupport-spinner%3A0.8.1
In my opinion the benefits outweight the costs. In version 0.9.0 those number will be a bit lower too.

`ListPreference` depends on <s>some stuff</s> everything except `XpAppCompatSpinner` from support-spinner. `ListPreference` is one of core components of preference system so I'm keeping it.

You're essentially asking me to strip out all the simple menu/simple dialog from `ListPreference` to some other class which would not be part of support-preference. Sicne we're going for that material design anyway, what's the point?

**Comment by dirkam** [comment]
In my case, I'm dancing with the 64K dex limit and I try to get rid off everything that is not mandatory. Since previous versions of `support-preference` didn't have `support-spinner` I thought that it's not mandatory if one only needs `support-preference`. But, if it is and `support-preference` won't work without it then it's fine and I'll live with that. Certainly, `ListPreference` is a must, but it was working before  `support-spinner` as well (yet, I understand that it now depends on `support-spinner`).

**Comment by consp1racy** [comment]
Understood.

Classes that are now in support-spinner were before in support-preference anyway.

**Comment by dirkam** [comment]
Yep, it's clear now, thanks for the explanation.
