### ISSUE TITLE
Preference items created at runtime losing style?

### ISSUE THREAD

**Issue by JoseGD** [consp1racy/android-support-preference#37]
I'm creating preference items at runtime under some category of my PreferenceScreen this way:

```
Preference pref = new Preference(getActivity());
pref.setKey("key");
pref.setTitle("title");
pref.setSummary("summary");
prefCategory.addPreference(pref);
```

It works but the preference loses its default style, showing the title with a big font size for example.
A similar preference created in XML is displayed correctly.

Any ideas how can I get those runtime items displayed correctly?

**Comment by consp1racy** [comment]
`getPreferenceManager().getContext()` instead of `getActivity()` in place of `Context`.

In other news: If you're manually inflating views for a dialog use this:

```
final AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
final Context context = builder.getContext();
final LayoutInflater inflater = LayoutInflater.from(context);
final View view = inflater.inflate(R.layout.whatever, null, false);
```

Same thing, use correct context for correct themes.

**Comment by consp1racy** [comment]
Secondly make sure you've imported `net.xpece.android.support.preference.Preference` rather than `android.support.v7.preference.Preference` if you want automatic tint capabilities or font color change.

**Comment by JoseGD** [comment]
Works like a charm. Thanks for your prompt response!
