### ISSUE TITLE
Customizing list preference

### ISSUE THREAD

**Issue by JoseGD** [consp1racy/android-support-preference#39]
Hi @consp1racy, I want to customize items in a `ListPreference` one by one, to achieve something similar to this: http://stackoverflow.com/questions/34707077/android-listpreference-as-font-size-picker-or-accessing-individual-views-of-lis

Is that code appropriate for the `ListPreference` implementation of this library?

Also, if I use the SimpleMenu style, where should I look to get a similar list item customization? I'm pretty sure the adapter works differently with SimpleMenu

**Comment by consp1racy** [comment]
So you need to inject a custom `SpinnerAdapter` into `ListPreference`...

I'll expose a `SpinnerAdapter buildAdapter(Context)` method on `ListPreference`. You'll then subclass it and provide your own adapter which would possibly be a subclass of `CheckedTypedItemAdapter<CharSequence>` which overrides `bindDropDownView(View, CharSequence)`.

The original adapter is constructed like this:

```
return new CheckedTypedItemAdapter<>(getContext(), R.layout.asp_simple_spinner_dropdown_item, android.R.id.text1, getEntries());
```

**Comment by consp1racy** [comment]
Current version allows you to override adapter only in simple menus. That was an oversight. Next release will allow you to supply you own adapter to simple dialogs as well.

# Change log

**1.0.1**
- `SpinnerAdapter ListPreference.buildAdapter(Context)` is deprecated in favor of:
  - `SpinnerAdapter buildSimpleMenuAdapter(Context)` - Used in simple menus.
  - `SpinnerAdapter buildSimpleDialogAdapter(Context)` - Used in simple dialogs.
  - Override the following methods to expose your data set:
    - `CharSequence[] getEntries()` - Item captions.
    - `CharSequence[] getEntryValues()` - Persisted item values.

**Comment by consp1racy** [comment]
Released.

**Comment by JoseGD** [comment]
Hey @consp1racy I definitely owe you a beer. Look at the beautiful menu I've done thanks to your latest changes :)

![borrar1](https://cloud.githubusercontent.com/assets/818784/17271455/a28cce94-5652-11e6-9514-c27c3e85a349.png)

**Comment by consp1racy** [comment]
Appreciated, just hope I don't break it in future :D
