### ISSUE TITLE
PreferenceFragment has incorrect margins

### ISSUE THREAD

**Issue by KennyGoers** [consp1racy/android-support-preference#4]
The Preference fragment doesn't have proper 16dp margins, they appear to be 8dp. Could be set in the activity but this would add white space to the edge. Not horrible, but repairable.

**Comment by consp1racy** [comment]
Can you test on 2.3.7, 4.1, 4.4, 5.1 and post screens? Thank you.

I'll look into it, sadly no sooner than in two weeks.

**Comment by consp1racy** [comment]
The preference fragment and its list all have zero margins/paddings. Preference items have 16dp and 24dp left and right paddings on phones and tablets respectively.
