### ISSUE TITLE
PreferenceManager.setDefaultValues failing to find classes

### ISSUE THREAD

**Issue by sir-earl** [consp1racy/android-support-preference#40]
I need to initialize the shared preferences from my prefs.xml file from an activity before the preference fragment is shown, but the call to setDefaultValues is failing with the following exception:

`android.view.InflateException: Binary XML file line #36: Error inflating class (not found)ColorPreference`

I assume this is happening because the PreferenceManager doesn't know about the correct package paths.

How would you recommend I solve this issue? Do I need to include the full class paths in the prefs.xml file?

**Comment by sir-earl** [comment]
I was able to solve the problem by making XpPreferenceManager public, copying the 'setDefaultValues' methods across from the base class, and changing them to instantiate XpPreferenceManager instead.

**Comment by consp1racy** [comment]
I see, I will provide `setDefaultValues` methods on `XpPreferenceManager` and make it public in the next release.

**Comment by consp1racy** [comment]
In other news I didn't even know this method existed, thank you so much for pointing this out!
