### ISSUE TITLE
ListPreference MenuMode question

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#43]
Hi,

Sorry for this, I'm sure that this is something on my end, but I just realized that none of my ListPreferences are working since migrating to 1.0.0 from 0.8.1. Now I'm on 1.0.2.

```
listPreference.buildSimpleDialogAdapter(getActivity());
listPreference.setMenuMode(ListPreference.MENU_MODE_SIMPLE_ADAPTIVE);
```

This works, but I want to stick to the normal Alert Dialog style. If I change the menu mode to dialog or simple dialog then nothing happens when I click on the preference.

This is how I use it in my preferences.xml

```
<ListPreference xmlns:app="http://schemas.android.com/apk/res-auto"
            android:icon="?attr/icSettingsProfile"
            android:key="settingsId"
            android:title="@string/settings_choose_profile"
            app:asp_iconPaddingEnabled="false" />
```

And this is the theme:

```
<style name="AppThemeSettingsDark" parent="AppThemeDark">
        <!-- Used to theme preference list and items. -->
        <item name="preferenceTheme">@style/PreferenceThemeOverlay.Material</item>
        <item name="alertDialogTheme">@style/AppThemeDark.Dialog.Alert</item>
        <item name="dialogTheme">@style/AppThemeDark.Dialog</item>
        <item name="asp_preferenceIconTint">?colorAccent</item>
        <item name="asp_preferenceDialogIconTint">?asp_preferenceIconTint</item>
    </style>

 <style name="AppThemeDark.Dialog" parent="Theme.AppCompat.Dialog">
        <item name="colorPrimary">@color/dark_primary</item>
        <item name="colorPrimaryDark">@color/dark_primary_dark</item>
        <item name="colorAccent">@color/dark_primary_accent</item>
        <!--<item name="android:textColorHighlight">@color/secondary_text_default_material_dark</item>-->
    </style>

    <style name="AppThemeDark.Dialog.Alert" parent="Theme.AppCompat.Dialog.Alert">
        <item name="colorPrimary">@color/dark_primary</item>
        <item name="colorPrimaryDark">@color/dark_primary_dark</item>
        <item name="colorAccent">@color/dark_primary_accent</item>
        <!--<item name="android:textColorHighlight">@color/secondary_text_default_material_dark</item>-->
    </style>
```

Thanks!

**Comment by consp1racy** [comment]
Hi, I'm going to need a bit more. Those two lines of code alone and even in this order make no sense. If you could **share a sample app** that would be great, if not, I'll need **at least the whole method** where you use this. I'm also going to need you to **better describe what is the expected and actual behavior**.

Code in question:

```
listPreference.buildSimpleDialogAdapter(getActivity());
listPreference.setMenuMode(ListPreference.MENU_MODE_SIMPLE_ADAPTIVE);
```

**Comment by consp1racy** [comment]
What's `?attr/icSettingsProfile`? I don't see this attribute defined in your theme.

You're not supposed to call `buildSimpleDialogAdapter` on your own, it's invoked by `XpListPreferenceDialogFragment`. You're supposed to subclass `ListPreference` and override it. I'm not sure what is your intention here, I'm going to need more information.

---

Here's the specialized implementation: https://github.com/consp1racy/android-support-preference/blob/master/sample/src/main/java/net/xpece/android/support/preference/sample/FontSizeListPreference.java

Here's the updated preference XML file: https://github.com/consp1racy/android-support-preference/blob/master/sample/src/main/res/xml/pref_data_sync.xml

This example class will show each entry with increasing size from 8sp to 24sp.

---

Custom adapters only work with `simple_dialog`, `simple_menu` and `simple_adaptive` menu modes. If you want the default platform behavior just set `app:asp_menuMode="dialog"` and you're good to go.

**Comment by dirkam** [comment]
I just want a plain old ListPreference in material style. This was working fine until the buildapater was exposed in the lib (at least I think this might be the reason).
`?attr/icSettingsProfile` for sure is not a problem, its defined in the parent theme. I have listpreferences without icons and those don't work either.

As described above, I have a preferences.xml with a couple of preferences, including some listpreferences.

In my SettingsFragment I extend `XpPreferenceFragment`. I declare `ListPreference listPreference`. In `onCreatePreferences2` I call `addPreferencesFromResource(R.xml.preferences);` and use `listPreference = (ListPreference) findPreference("settingsId");` I load the values from a database with `listPreference.setEntries()` and `listPreference.setEntryValues()`.
And that's it. That is how I used to use ListPreference from your library. But with the latest versions if I click on the listpreference then nothing happens. The dialog does not open. (onpreferenceclick is called, though)
However if I do the following:

```
listPreference.buildSimpleDialogAdapter(getActivity());
listPreference.setMenuMode(ListPreference.MENU_MODE_SIMPLE_MENU);
```

Then the simple menu dialog is opened, but unfortunately this is not what I want, I would like to see the normal alert dialog style, which does not work for me.

I hope this is clear, let me know if you need anything else. I'm sure I'm doing something wrong.

**Comment by consp1racy** [comment]
I just tested the following code in the sample app and it works as expected. Opens a material themed dialog with a title and radio buttons with no item pre-selected.

### preference.xml

```
<ListPreference
    android:icon="@mipmap/ic_launcher"
    android:key="sync_frequency2"
    android:title="@string/pref_title_sync_frequency"
    app:asp_iconPaddingEnabled="false"/>
```

### SettingsFragment.onCreatePreference2

```
    ListPreference sync_frequency2 = (ListPreference) findPreference("sync_frequency2");
    sync_frequency2.setEntries(new String [] {"1 hour", "2 hours"});
    sync_frequency2.setEntryValues(new String [] {"60", "120"});
```

If that doesn't work there must be something else wrong.

**Comment by dirkam** [comment]
Thanks a lot for taking your time testing it, I really appreciate it. Based on this I tried to look elsewhere and it turned out that I made a mistake in `onPreferenceDisplayDialog`. As it has changed with the newer versions as well I had to migrate from `onDisplayPreferenceDialog2` and I made an error there.
Now it works fine.
