### ISSUE TITLE
SeekBarPreference

### ISSUE THREAD

**Issue by waterdaan** [consp1racy/android-support-preference#45]
Thanks so much for this library!!!!
I´m using the SeekBarPreference in my app
I had to change onStopTrackingTouch if mPreferredMin isn´t 0, but maybe i was using it wrong

```
@Override
public void onStopTrackingTouch(SeekBar seekBar)
{
    mTrackingTouch = false;
    if (seekBar.getProgress() + **mPreferredMin**  != mProgress)
    {
        syncProgress(seekBar);
    }
    if (mOnSeekBarChangeListener != null)
    {
        mOnSeekBarChangeListener.onStopTrackingTouch(seekBar);
    }
}
```

**Comment by consp1racy** [comment]
Thank you,

Yes, I believe you did it correctly. The thing is `ProgressBar` itself does not support setting minimum value. It goes from `0` to `android:max`. So you have to offset the output value by your minimum value.
