### ISSUE TITLE
Preference widget for numbers

### ISSUE THREAD

**Issue by JoseGD** [consp1racy/android-support-preference#46]
I know this library doesn't have a number picker, then which is the suggested widget for inputting numbers?
Just use `EditTextPrefence`?
(sorry if this is a silly question :)

**Comment by consp1racy** [comment]
Coorect, the only included preference that could satisfy your needs would be `EditTextPreference`. If you'd like a number picker you can take a shot at making a custom dialog preference.

**Comment by JoseGD** [comment]
For the record, I ended up using `SeekBarPreference`, since the current AppCompat's implementation of `EditTextPreference` has so many issues with number input.

I wanted to offer a preference for font sizes, and after seeing Nova Launcher using seekbars for this case, I followed suit.

**Comment by consp1racy** [comment]
Good idea, that didn't even cross my mind.

What are the issues with AppCompatEditText number input? I feel so in dark :D

**Comment by JoseGD** [comment]
Mainly, that EditText ignore `InputType` values. You cannot show a numeric keyboard like you can with the non-AppCompat equivalent. There is even a library to fix this: https://github.com/Gericop/Android-Support-Preference-V7-Fix. Apparently Google fixed the problme in some way in one of the latest AppCompat versions, but I didn't have the time to investigate further.

**Comment by consp1racy** [comment]
Actually you can do this with my library. From README.md:

Use EditTextPreference.setOnCreateEditTextListener(OnCreateEditTextListener) to setup your input field.

You have to do it in Java but it works.

Reason is the EditText widget is created at the time when the dialog is created so the preference XML parser is already finished so you cannot read the attributes directly from the preference XML.

**Comment by JoseGD** [comment]
Ops... as I said, I was short of time. Thanks for pointing it out.
Anyway, users were ok with the sliders for selecting sizes :)
