### ISSUE TITLE
Feature request: long clickable preference

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#47]
Would it be possible to add long click listeners for preferences? Thanks.

**Comment by consp1racy** [comment]
Maybe, can you provide some use cases?

**Comment by dirkam** [comment]
In my case I would use it to reset a preference to its default value. I have several Preferences that the user can click on to make some changes (e.g. one of them starts the barcode reader and the returned value is saved) but I need to have an option to reset these to the default value individually. Long clicking on the Preference would just make sense so there is no need for separate controls.

Let me know what you think, I hope you find it useful.

**Comment by consp1racy** [comment]
Hmm, a long click action seems too obscure to me. Take for example TabLayout or Toolbar where long click shows item description. A destructive action seems unexpected to me as a user. However I have encountered this before in an app specification, that being said there was a tutorial UI explaining how the widget in question worked).

A much better design (IMO) would be adding another `Preference` with appropriate title and description which would clear the bar code preference data.

Considering the framework does not support this behavior and it looks like an antipattern to me I'm prone to not implementing this. Thoughts?

**Comment by dirkam** [comment]
I still think it would be useful and it would be easy to add a note to the preference summary that long press will reset its value to default (or whatever that action is, it can be up to the developer)
In my case I have like 10 such preferences where I would use this feature, adding a reset preference for each just would create a mess.
Besides it's not like providing a different behavior for long press as currently there is no action for such event, so I'd not call it an anti-pattern (though I understand your point that it's not part of the framework by default).

What do you think?

**Comment by consp1racy** [comment]
Fair enough, I'll look into it.

**Comment by consp1racy** [comment]
Released in v1.0.3.

**Comment by dirkam** [comment]
Omg, you rock! Will test it soon. Thanks!

**Comment by dirkam** [comment]
Just wanted to confirm that it works like a charm. thanks again!
