### ISSUE TITLE
question: Audio (music) picker preference

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#50]
Is it possible to have a preference that works similar to the Ringtone preference but shows all the Audio files that is on the device (with some kind of structure, like Artists in ascending order or something)? When the item is clicked the sound should be played.
This can be achieved with using a picker Intent but I have a lot of issues that 3rd party apps return URIs in various formats so I'd like to have something done natively.

**Comment by consp1racy** [comment]
That doesn't sound as a use case for a simple picker.

I don't see how introducing another layer would remove the Uris provided by the original apps.

Intent does sound like the best tool for it. Read:
https://commonsware.com/blog/2016/09/06/virtual-files-faq.html
http://stackoverflow.com/questions/1698050/multiple-mime-types-in-android
This should allow you to pick a music file, make a local copy of it and work with that.
