### ISSUE TITLE
Title/Subtitle tinting 

### ISSUE THREAD

**Issue by usernotnull** [consp1racy/android-support-preference#51]
Does the library support title and summary tinting as it support icon tinting? 
In my app when i disable a dependency, the children's title color stays the same and only the icons change tint.

**Comment by consp1racy** [comment]
> Does the library support title and summary tinting as it support icon tinting? 

Yes.

> In my app when i disable a dependency, the children's title color stays the same and only the icons change tint.

You have to use a ColorStateList.

https://developer.android.com/guide/topics/resources/color-list-resource.html
http://stackoverflow.com/questions/11225166/android-textcolor-of-disabled-button-in-selector-not-showing

Default text color is taken from theme's `android:textColorPrimary` and `android:textColorSecondary`. Default text colors for light and dark themes are provided by AppCompat and include a faded color for disabled state. I strongly encourage you to override these theme attributes to maintain consistent looks.

**Comment by usernotnull** [comment]
> Default text color is taken from theme's android:textColorPrimary and android:textColorSecondary. 

That's what I needed to know. Thanks!
