### ISSUE TITLE
Crashes with the native Switch on specific devices

### ISSUE THREAD

**Issue by inorichi** [consp1racy/android-support-preference#52]
Hi, I'm getting crashes [from an user of my app](https://github.com/inorichi/tachiyomi/issues/528) when using `SwitchPreference` with the native switch on specific devices, the crash is from a Verizon Ellipsis 10 tablet with API 22, but others may be affected as well.

[Here's a full stack trace.](https://paste.kde.org/p1876jigb/ikw4m1)

I investigated it and I've found out that for some reason the attribute `mShowText` in `android.widget.Switch` is set to true, and that leads to a crash at the beginning of the method `makeLayout`.

One possible fix would be to set `android:switchTextOn` and `android:switchTextOff` to an empty string in the xml resource, but the developer must be aware of it and it's quite ugly.

Another possible fix is to update the method [syncSwitchView](https://github.com/consp1racy/android-support-preference/blob/master/library/src/main/java/net/xpece/android/support/preference/SwitchPreference.java#L133) and call `switchView.setShowText(false)` for the native one, but I don't know if the crash happens after or before binding the view so it may not work.

I also don't know why the `SwitchPreference` class from the support library included the switch text, since AFAIK it's never shown (it always uses the text from the preference, not the widget).

**Comment by consp1racy** [comment]
There's nothing to fix. If you set `android:showText="true"` but don't set `android:textOn` and `android:textOff` (or set tem to `null` in Java), you're going to get NPEs. This is how `Switch` works.

Either the platform supplied default style for `Switch` or your overridden theme's `android:switchStyle`  have set `android:showText="true"`.

Possible solution would be to copy `res/layout/asp_preference_widget_switch.xml` and `res/layout-v21/asp_preference_widget_switch.xml` from my library to your project and explicitly set `android:showText="false"`.

The text (albeit not shown) is used for accessibility.

**Comment by inorichi** [comment]
I didn't override the theme (and in every device except this one `showText` is set to false as expected) so they may have changed the default style. Since they are most probably going to get a crash even with your sample app I thought it could be fixed here, but I guess I'll do as you say and copy those resources.

Thanks for your help!

**Comment by consp1racy** [comment]
Finally! :D
> Known issues
> SwitchPreference does not animate its SwitchCompat widget when clicked.
https://code.google.com/p/android/issues/detail?id=196652
This is hotfixed in v0.7.0 on Android 5 or later by using native Switch instead of SwitchCompat. This may introduce other problems along the way so don't rely on this change.

Yup, the manufacturer probably supplied butchered material design theme.

Your other option is having the same layout in `layout-v21` as in `layout` since that one uses `SwitchCompat` which shouldn't be affected.

Thanks for calling out.

**Comment by inorichi** [comment]
For now I've only included `layout-v21` and set `android:showText="false"` there. I just hope they only updated the theme and not modified the sources, ~~in which case I'll end up cloning your lib and setting an empty string.~~

I started using your library because of the switch animation issue and the absence of MultiSelect unless you used `preferences-v14` (which made me use native Fragments and added more bugs and headaches). I don't want to give up on animated switches yet. :)

Thanks a lot for the effort you have put into making this great lib.

Edit: Adding `android:textOn=""` and `android:textOff=""` to `layout-v21` might work too, I shouldn't need to clone the lib.

**Comment by consp1racy** [comment]
The lib uses style framework, open styles.xml and themes.xml in the lib to better inderstand how it's all connected, and leverage it for your own adjustments. In any case you don't need to clone the lib for this.

The SwitchCompat animation in RecyclerView is a known issue in support libs. There's a link to bugtracker at the bottom of readme.

**Comment by inorichi** [comment]
I guess I didn't explain myself very well.

> The lib uses style framework, open styles.xml and themes.xml in the lib to better inderstand how it's all connected, and leverage it for your own adjustments. In any case you don't need to clone the lib for this.

I was talking about the theme and source code of the `Switch` class of the specific device getting the crashes. Your lib is totally not at fault here.

As I edited later adding an empty string to `textOn` and `textOff` to the resource I've already modified (`res/layout-v21/asp_preference_widget_switch.xml`) will be enough in the unlikely case the setting `android:showText="false"` is overriden by the platform if they have changed the source code like Samsung usually does.

> The SwitchCompat animation in RecyclerView is a known issue in support libs. There's a link to bugtracker at the bottom of readme.

I was aware of that issue. I read the entire readme around 6 months ago (when I included it) and as I said in my previous comment that issue was one of the reasons I migrated to your lib.


Edit: Sorry for all the noise btw.

**Comment by consp1racy** [comment]
Switch class was the same as in AOSP, line numbers checked out.

This is probably my fault, i should've checked the API 21 platform SwitchPreference instead of just changing the classes.

I'll look into it.

**Comment by inorichi** [comment]
Thanks a lot. 👍 

Not related to this issue but I'm getting this error when upgrading to either `1.1.0` or `1.1.1`.

```
Error:Failed to resolve: xpece-android-support-preference:support-spinner:unspecified
``` 

I'm not using the spinner dependency, and adding it doesn't help either. I tried in an empty project and it also happens there.

**Comment by consp1racy** [comment]
Yep, my fault, sorry.

Please use version 1.2.0 which was just pushed out. I'll update README.md shortly.
