### ISSUE TITLE
Can't download version 1.2.0

### ISSUE THREAD

**Issue by LookedPath** [consp1racy/android-support-preference#53]
I've tried using the latest version (1.2.0) but Gradle couldn't find it so I manually searched in the repository and it's actually missing.
The latest version available is 1.1.1 as you can see from this [link](http://jcenter.bintray.com/net/xpece/android/support-preference).
Thank you for you work and I hope that you can fix this.
Without your library a lot of people would just get mad implementing preferences.

**Comment by consp1racy** [comment]
Thank you for reporting this, it's back up and running. Sorry for the inconvenience.
