### ISSUE TITLE
edittextpreference

### ISSUE THREAD

**Issue by meddd** [consp1racy/android-support-preference#56]
it is posibility to style the edittextpreference. I have try a lot of solution but it has no effect.
in your sample, there is orange button, but in dialog of edittextpreference, the text is blue, and ich multicheckbox, they are also blue

**Comment by consp1racy** [comment]
The dialogs pickup `?alertDialogTheme` of the activity.

The sample project looks like this:

    <color name="primary">@color/light_green_700</color>
    <color name="primary_dark">@color/light_green_900</color>
    <color name="accent">@color/amber_a700</color>
    <color name="accent_alt">@color/light_blue_a400</color>

    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>

        <item name="alertDialogTheme">@style/AppTheme.Dialog.Alert</item>

        <item name="preferenceTheme">@style/PreferenceThemeOverlay.Material</item>

        <item name="asp_preferenceIconTint">?colorAccent</item>
        <item name="asp_preferenceDialogIconTint">?asp_preferenceIconTint</item>
    </style>

    <style name="AppTheme.Dialog.Alert" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent_alt</item>
    </style>

**Comment by meddd** [comment]
Thank You.
