### ISSUE TITLE
CheckBoxPreference is missing Constructor with only Context

### ISSUE THREAD

**Issue by corwin42** [consp1racy/android-support-preference#57]
See subject.

The CheckBoxPrefence Class has not Constructor with only the Context as parameter. All other classes have this.

**Comment by consp1racy** [comment]
Thanks for reporting. I'll take care of this in the next release.

In the meantime use `new CheckBoxPreference(context, null)` which is an equivalent.

**Comment by consp1racy** [comment]
Released just now in v1.2.3.
