### ISSUE TITLE
Icon tinting if Preference is created programatically

### ISSUE THREAD

**Issue by corwin42** [consp1racy/android-support-preference#58]
If I create the preferences by xml I can add
`app:asp_dialogTintEnabled="true"` and `app:asp_tintEnabled="true"` to enable automatic Icon tinting for the preference item and the dialog.

I have to create my preference Items programatically. Is there a simple way to enable the icon tinting if the preference item is created by code? The mPreferenceIconHelper is private so I can't use it to enable the automatic tinting.

The only solution I found is to set the Icon tint manually with `setSupportIconTintList()`

**Comment by consp1racy** [comment]
I see, the methods controlling tinting enabled state on Preferences are missing. Thanks for reporting this, I'll add them.

In the meantime use `PreferenceIconHelper.setup(Preference pref, @DrawableRes int icon, @ColorRes int tint, boolean padding)` or whatever else is working for you right now.

**Comment by consp1racy** [comment]
Just released in 1.2.3.

    Preference.setSupportIconTintEnabled(true)

**Comment by corwin42** [comment]
Thank you very much for your fast fix.
