### ISSUE TITLE
Must Implement onWindowStartingSupportActionMode(Callback)

### ISSUE THREAD

**Issue by McPo** [consp1racy/android-support-preference#6]
When extending from net.xpece.android.support.preference.AppCompatPreferenceActivity, the following error message is raised.

```
Error:(45, 8) error: SettingsActivity is not abstract and does not override abstract method onWindowStartingSupportActionMode(Callback) in AppCompatCallback
```

I was previously using 22.2.0 appcompat version but rolling back to 22.1.1, also didn't work. In the end needed to implement. (Your sample doesn't include this)

```
@Nullable
    @Override
    public ActionMode onWindowStartingSupportActionMode(ActionMode.Callback callback) {
        return null;
    }
```

Everything is working, fine.
Great lib, cheers for the effort put into it.

**Comment by consp1racy** [comment]
Thank you for your support, just fixed this in 0.4.3.
