### ISSUE TITLE
Custom listpreference

### ISSUE THREAD

**Issue by meddd** [consp1racy/android-support-preference#63]
when I used custom listpreference this way:
<com.cos.android.samples.PreferenceCustomListPreference
		android:key="imageList"
		android:title="Title"
		android:summary="Summary"
		android:entries="@array/listNames"
		android:entryValues="@array/listValues"
		cos:entryImages="@array/imageValues"		/>
i have got error:
android.view.InflateException: Binary XML file line #6: Error inflating class com.cos.android.samples.PreferenceCustomListPreference

It is posible to use custom listpreference?

when aI used without android-support-preference everything is OK, working.

**Comment by consp1racy** [comment]
Please post 

 * full stack trace,
 * what version of android did this happen on
 * what version of support libraries did you use
 * if that doesn't help me I'll ask for `PreferenceCustomListPreference` source.

This apragraph in README.md may help you:

> ### ListPreference custom adapter
> If you subclass `ListPreference` you can supply your own `SpinnerAdapter` which may or may not
use `getEntries()` as its data set. Here follow the methods you need to override:
> - `SpinnerAdapter buildSimpleMenuAdapter(Context)` - Used in simple menus.
> - `SpinnerAdapter buildSimpleDialogAdapter(Context)` - Used in simple dialogs.
> - Override the following methods if your `SpinnerAdapter` does *not* use `getEntries()` as data set:
>   - `CharSequence[] getEntries()` - Item captions.
>   - `CharSequence[] getEntryValues()` - Persisted item values.

**Comment by meddd** [comment]
Evrything is ok. I have used wrong library.
