### ISSUE TITLE
How to listen for preference status changes?

### ISSUE THREAD

**Issue by goldmont** [consp1racy/android-support-preference#67]
Hi,

I need to know when a preference gets disabled due to dependency. Is there a listener? Thanks

**Comment by consp1racy** [comment]
You can attach a listener to the dependency.

    checkBoxPreference.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
        @Override
        public boolean onPreferenceChange(Preference preference, Object newValue) {
            // Do something here...
            return true; // This change is valid, continue.
        }
    });

There's a `onDependencyChanged` method in `Preference` but extending a class is not a recommended option.

**Comment by goldmont** [comment]
For example:
I have three CheckBoxes and, the last two, depend by the first. When the first gets unchecked, the other two CheckBox get disabled. When the last two CheckBoxes get disabled, I would change their summary. How can I do? Your help will be very appreciated.

**Comment by consp1racy** [comment]
```
checkBoxPreference1.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
    @Override
    public boolean onPreferenceChange(Preference preference, Object newValue) {
        final boolean checked = (boolean) newValue;
        if (!checked) {
            checkBoxPreference2.setSummary("Something");
            checkBoxPreference3.setSummary("Something else");            
        }
        return true;
    }
});
```

Note: You have to return true to indicate that the changed value is valid and should be processed. Sorry for the confusion.

**Comment by goldmont** [comment]
I managed to solve the problem! Thank you man.
