### ISSUE TITLE
Search in preferences like in Nougat

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#69]
Would it be possible to add a search field like in Nougat?
![image](https://cloud.githubusercontent.com/assets/6302839/26568773/7af65b2c-4506-11e7-84fa-228467e0e687.png)
_Image source: http://www.greenbot.com/article/3110627/android/how-to-navigate-the-new-settings-menu-in-android-nougat.html_

**Comment by consp1racy** [comment]
On the side of UI: The preference fragment just contains preferences and is typically located under the app bar. Any extra functionality such as search, action buttons, hamburger menu is out of scope.

On the side of implementation: There is no one good for everything filter. the one in screenshots works by checking preference title, I can't guarantee that's good for everyone. The implementation is best left to consumers.
