### ISSUE TITLE
Where's XpAppCompatSpinner.setEntries(String[] entries) method?

### ISSUE THREAD

**Issue by anggrayudi** [consp1racy/android-support-preference#73]
Hi there, I'm facing issue while changing `XpAppCompatSpinner` entries dynamically. I didn't find any method related to  `setEntries(String[] entries)`. I hope you can add this one.

Thank you.

**Comment by consp1racy** [comment]
Hi, according to https://developer.android.com/guide/topics/ui/controls/spinner.html there isn't such method in the original API.

Currently I'm not planning to add it. But a helper method achieving it could look like this:
    
    public static void setEntries(final Spinner spinner, @ArrayRes final int entriesResId) {
        final Context context = spinner.getContext();
        final CharSequence[] entries = context.getResources().getTextArray(entriesResId);
        final CheckedTypedItemAdapter<CharSequence> adapter = new CheckedTypedItemAdapter<>(context, android.R.layout.simple_spinner_item, android.R.id.text1, entries);
        adapter.setDropDownViewResource(R.layout.asp_simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
    }

    public static void setEntries(final Spinner spinner, final CharSequence[] entries) {
        final Context context = spinner.getContext();
        final CheckedTypedItemAdapter<CharSequence> adapter = new CheckedTypedItemAdapter<>(context, android.R.layout.simple_spinner_item, android.R.id.text1, entries);
        adapter.setDropDownViewResource(R.layout.asp_simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
    }

This code will get you proper theming in popup and dialog mode and will highlight slected item.

I'll leave this open and may implement it later.

**Comment by consp1racy** [comment]
Published in 1.2.8 just now
