### ISSUE TITLE
A top positioning issue for the simple menu.

### ISSUE THREAD

**Issue by serhii-k** [consp1racy/android-support-preference#74]
Dear @consp1racy ,

First of all, thank you for this amazing library! It really helps me a lot.

I have noticed one issue though. If the first preference is a ListPreference with a simple menu, its top is limitted with the parenting frame, and not the top edge of the screen. So it appears below the app bar.

As an example, in the sample app I moved the dana_sync prefs above the general prefs:
addPreferencesFromResource(R.xml.pref_data_sync);
addPreferencesFromResource(R.xml.pref_general);

So, it looks like this:

![screenshot_1501234729](https://user-images.githubusercontent.com/10563821/28712300-6089432e-7393-11e7-9325-d53924648677.png)

I hope it's not a big issue.

**Comment by consp1racy** [comment]
Hi @serhii-k, I'm glad the library helps you and you like it.

> If the first preference is a ListPreference with a simple menu, its top is limitted with the parenting frame, and not the top edge of the screen.

Turns out I thought of that ages ago when I built this :D

Add `android:adjustViewBounds="false"` to the preference and it will be constrained to the window rather than the recycler view.

**Comment by serhii-k** [comment]
Oh, awesome! Thank you very much, @consp1racy !
