### ISSUE TITLE
RTL preference layout doesn't work when description has more than one line

### ISSUE THREAD

**Issue by javmarina** [consp1racy/android-support-preference#77]
The issue is easy to reproduce. Create some preferences, some with one-line descriptions and the others with longer descriptions. If you go to developer options and enable RTL direction, you can see that preferences with long descriptions don't behave correctly. To be precise, the description text view is aligned to the left instead to right, which is the expected behaviour. Surprisingly, this also happens in the stock Settings app, so I'm going to report this to Google

**Comment by consp1racy** [comment]
Preference text views are `wrap_content` so it's hard to catch but once you go multiline it is aligned to left. Preference categories are match_parent, so they're always left.

I've made the adjustments and will push a new version before Monday.
`

**Comment by consp1racy** [comment]
For completeness:

The thing is English text will get aligned to left by default. If the contents of the TextView were Arabic, it would be drawn correctly. The issue only presents itself when testing RTL with English or showing English text.

By English I mean any LTR script.

If we tested Arabic multi-line text it would be right aligned.

**Comment by javmarina** [comment]
I didn't know that. Seems like not a big issue. Anyway, thank you so much for the fast response!

**Comment by consp1racy** [comment]
Published in 1.2.8 just now.
