### ISSUE TITLE
PreferenceIconHelper setIcon() with Drawable parameter and tint with ColorInt

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#78]
I'd like to change the color of all the preference icons runtime. Since there are a lot of preferences with icons the best would be to iterate through the whole preference list and if a given preference has icon then I'd set the color with
```
PreferenceIconHelper.setup(p /* preference */,
                        p.getIcon() /* icon as Drawable */,
                        colorInt /* tint as ColorInt*/,
                        true /* padding */);
```

Is there a way to achieve this with the current version of the lib? As far as I can see the tinting methods only accept Drawable and Color resource ids.

Thanks!

**Comment by dirkam** [comment]
Is it possible to change CheckBoxPreference tint runtime?

**Comment by consp1racy** [comment]
I think for coloring icons you could use this:

```
var d = AppCompatResources.getDrawable(preference.context, R.drawable.some_icon)
d = DrawableCompat.wrap(d)
DrawableCompat.setTint(d, someColorInt)
XpPreferenceHelpers.setSupportIcon(preference, d)
```

Changing `CheckBox` color/drawable at runtime *will* be a pain in the ass. You'd have to extend the `CheckBoxPreference` and override the `onBindViewHolder` method. And provide a setter for the color, of course.

**Comment by dirkam** [comment]
Thanks for your help, I'll look into this.
