### ISSUE TITLE
PreferenceFragment and AppCompat.

### ISSUE THREAD

**Issue by felipecds** [consp1racy/android-support-preference#8]
It`s possible extends from Fragment from support library? I'm using Navigation View on a project and all fragmens needs extending android.support.v4.app.Fragment

**Comment by consp1racy** [comment]
As long as you don't need to support devices older than Android 3 you can use native fragments alongside support fragments. That being said the next version of this library will probably exchange its base to recently introduced support-preference-v7 (based on support fragments).

**Comment by consp1racy** [comment]
Beware, the new version 0.5.0 uses preference-v7 as its base instead of native preference which will require you to change some things on your end (mostly just using XpPreferenceFragment instead of AppCompatPreferenceActivity).
