### ISSUE TITLE
Can it generate to tablet as OnePreference?

### ISSUE THREAD

**Issue by jrcacd** [consp1racy/android-support-preference#83]
[OnePreference](https://github.com/saurabharora90/OnePreference)

This is what's keeping me from moving to this library

**Comment by consp1racy** [comment]
Hi, the main goal of this library is to add these missing features to the preference-v7 support library:
+ leverage appcompat-v7 support library and Material Design on all devices,
+ add preference classes that are present in the framework but aren't public or aren't backported in the preference-v7 support library.

[Preference headers](https://developer.android.com/guide/topics/ui/settings.html#PreferenceHeaders) we're intentionally left out from preference-v7 and can be emulated 
+ by using a custom screen layout on tablets,
+ by following this official statement:

> One thing you’ll note *isn’t* in here is preference headers and you’d be totally right. However, that doesn’t mean a single list of preferences need to span a 10” tablet screen. Instead, your Activity can implement OnPreferenceStartFragmentCallback (http://goo.gl/IZWZBP) to handle preferences with an `app:fragment` attribute or `OnPreferenceStartScreenCallback` (http://goo.gl/CFp5Cr) to handle `PreferenceScreen` preferences. This allows you to construct a ‘header’ style `PreferenceFragmentCompat` in one pane and use those callbacks to replace a second pane without working in two separate types of XML files.

Source: https://plus.google.com/+AndroidDevelopers/posts/9kZ3SsXdT2T

As you can see your goal is fairly easy to achieve without making changes to the library. Good luck!
