### ISSUE TITLE
The popup exit transition seems doesn't work.

### ISSUE THREAD

**Issue by serhii-k** [consp1racy/android-support-preference#98]
Hello Eugen,

Wow! I noticed yesterday that you released the 2nd version of this amazing library. Many thanks for your hard work!!!

I have noticed one minor thing that I would like to report.

I was looking forward for the smooth transitions for popup menus. And the custom enter transition looks so nice!!! However, it looks like the exit transition doesn't work... I've tried to run the sample project on my phone (Huawei Honor 8, Android 7.0) and instead of the exit transition a popup just disappears instantly. I tried to increase the animator duration to 10x, and yep, there is no exit transition.

At first I thought it's just some "optimization" on my phone. But, I also tried the sample on the Android emulator (7.1.1 Google APIs). And the exit transition also doesn't work on the emulator.

Probably you know about this issue. Or I should have done some adjustments to make it work... I didn't have much time to play with it. But the fading out transition in styles.xml (v23) seems doesn't work.

Kind regards,
Serhii

**Comment by consp1racy** [comment]
Hi,

thanks for the praise and the issue report.

I just tried the latest version (2.1.1) in an API 27 and 23 emulator and the exit transition worked as expected.

Could you provide a screen record and try on Android emulator API 27 and 23?

Thanks!

**Comment by serhii-k** [comment]
Hi Eugen,

I've just updated all building, platform and emulator tools, and have done a clean rebuild of the 2.1.1 sample. And also I've downloaded the latest versions of emulators API 23, 25, and 27.

I can confirm that everything works excellently on emulators API 23 and API 27. Both enter and exit transitions work smoothly.

But on my device with Android 7.0 and on the emulator API 25 (7.1.1 x86 with Google APIs) the exit transition doesn't work.

Here are recordings from my device (a zip-file with a video inside) and from the emulator. I've increased the duration of animations 10x in the developer settings.

Device (API 24):

[Android_7.0_Huawei_Honor_8.zip](https://github.com/consp1racy/android-support-preference/files/1819490/Android_7.0_Huawei_Honor_8.zip)

Emulator (API 25):

![7 1 1_x86_google_apis](https://user-images.githubusercontent.com/10563821/37525491-aefe3a98-2935-11e8-9119-258e415e5ee2.gif)

**Comment by consp1racy** [comment]
Crap, you're right. The exit transition doesn't happen on API 24-25.

On these devices the transition isn't run if the popup window is not attached to an anchor view. And that's the case for us, since using an actual anchor view would result in wrong position.

I'll release a fix over the weekend.

**Comment by serhii-k** [comment]
Great! I'm really glad that you know the case and the solution.

**Comment by consp1racy** [comment]
If you want, you can get the fix on jitpack.io right now:

    repositories {
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        compile 'com.github.consp1racy:android-support-preference:50fc96ce10'
    }

An official release will come later, don't know when yet.

Thanks again for the report and good luck.

**Comment by serhii-k** [comment]
Awesome! Thank you very much, Eugen!
